### ISSUE TITLE
Can change brackets color

### ISSUE THREAD

**Issue by brisa** [bartosz-antosik/vscode-quietlight-plus#1]
I tried to change the color from yellow to something more visible to no avail.

**Comment by bartosz-antosik** [comment]
Hi!

Brackets in my example are colorized by an extension [Bracket Pair Colorizer](https://github.com/CoenraadS/BracketPair). Originally they have this color:

![image](https://user-images.githubusercontent.com/20492548/45676327-cb18ec80-bb31-11e8-9083-ebfb965fa5df.png)

To say the truth I have no idea whether it is possible to change colors of the brackets in the theme.
